🎉 feat(i18n): add german translations
add language selection dropdown
update de.json locale content

🐞 fix(ui): fix eslint, ts, ui errors

Fix: Error message "error:0308010C:digital envelope routines::unsupported"
Solution: Update dependencies and run npm audit fix
Context: https://stackoverflow.com/a/73027407

Fix: React injecting iframe with max z-index on reload after changes (development)
Solution: Update react-scripts to 5.0.1 or higher / Add resolutions in package.json "react-error-overlay": "6.0.9"
Context: https://stackoverflow.com/questions/69051008/react-injecting-iframe-with-max-z-index-on-reload-after-changes-development

Fix: TS error in src/api/services/index.tsx:1:8 Module has no default export
Solution: Commented out default import in src\api\services\index.tsx

Fix: eslint error, src\pages\AccessDenied\index.tsx, Line 35:30:  Unexpected empty arrow function  @typescript-eslint/no-empty-function
Solution: Add /* tslint:disable:no-empty */

Fix: eslint error, src\i18n\i18n.tsx, Line 16:3:  Do not use "@ts-ignore" because it alters compilation errors  @typescript-eslint/ban-ts-comment, Property ‘userLanguage’ does not exist on type ‘Navigator’
Solution: Remove @ts-ignore and add custom type NavigatorWithUserLanguage using intersection type with Navigator